# This is an attempt for re-building config and required files for
# every Doom or packages update.

name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        emacs-version: [snapshot]
        dist:
          - arch
          - ubuntu
          - macos
        include:
          - dist: arch
            os: ubuntu-latest
            home: "/root"
            container: archlinux:latest

          - dist: ubuntu
            home: "~"
            os: ubuntu-latest

          - dist: macos
            home: "~"
            os: macos-latest

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Install Arch dependencies
        if: matrix.dist == 'arch'
        run: pacman -Syu --noconfirm git openssh base-devel emacs-wayland tree

      - name: Install Mac dependencies
        if: matrix.dist == 'macos'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install tree

      - name: Checkout (manual for Arch)
        if: matrix.dist == 'arch'
        run: |
          git clone https://github.com/${{ github.repository }} doom-d
          cd doom-d
          git checkout ${{ github.sha }}
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - uses: actions/checkout@main
        if: matrix.dist != 'arch'
        with:
          path: doom-d
          submodules: recursive

      - name: Checkout doomemacs
        uses: actions/checkout@main
        with:
          repository: doomemacs/doomemacs
          submodules: recursive
          path: emacs-d-tmp
          fetch-depth: 1

      - run: whoami && id

      - name: move files
        run: |
          mv -v $GITHUB_WORKSPACE/doom-d ${{ matrix.home }}/.doom.d
          cp -rv $GITHUB_WORKSPACE/emacs-d-tmp ${{ matrix.home }}/.emacs.d

      - name: Cache Emacs
        if: matrix.dist != 'arch'
        uses: actions/cache@v3
        id: emacs-cache
        with:
          path: /usr/local/emacs/
          key: emacs-${{ matrix.emacs-version }}

      - name: Install Emacs
        if: matrix.dist != 'arch' && steps.emacs-cache.outputs.cache-hit != 'true'
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Install Doom
        run: |
          cd ${{ matrix.home }}
          ${{ matrix.home }}/.emacs.d/bin/doom install --force --no-fonts --no-env --verbose

      - run: tree -a ${{ matrix.home }}
      - run: cd ${{ matrix.home }} && ls -la

      - name: Create tar archive
        run: |
          cd ${{ matrix.home }}
          tar -czf ${{ matrix.home }}/release-${{ matrix.dist }}.tar.gz .emacs.d/.local

      # - run: cd ~ && ls -la

      - name: Upload release artifact
        uses: actions/upload-artifact@main
        with:
          name: release-${{ matrix.dist }}
          path: ${{ matrix.home}}/release-${{ matrix.dist }}.tar.gz

      # - run: ls -al $HOME/.emacs.d

      # - run: diff -qr doom-tmp $HOME/.emacs.d

