# This is an attempt for re-building config and required files for
# every Doom or packages update.

name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        emacs-version: [snapshot]
        dist:
          - arch
          # - ubuntu
          - macos
        include:
          - dist: arch
            os: ubuntu-latest
            container: archlinux:latest

          # - dist: ubuntu
          #   os: ubuntu-latest

          - dist: macos
            os: macos-latest

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Install Arch dependencies
        if: matrix.dist == 'arch'
        run: pacman -Syu --noconfirm git openssh base-devel emacs-wayland

      - name: Checkout (manual for Arch)
        if: matrix.dist == 'arch'
        run: |
          git clone https://github.com/${{ github.repository }} doom-d
          cd doom-d
          git checkout ${{ github.sha }}
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - uses: actions/checkout@main
        if: matrix.dist != 'arch'
        with:
          path: doom-d
          submodules: recursive

      - name: Checkout doomemacs
        uses: actions/checkout@main
        with:
          repository: doomemacs/doomemacs
          path: doom-tmp
          fetch-depth: 1

      - run: mv doom-d ~/.doom.d
      - run: cp -r doom-tmp ~/.emacs.d

      - name: Cache Emacs
        if: matrix.dist != 'arch'
        uses: actions/cache@v3
        id: emacs-cache
        with:
          path: /usr/local/emacs/
          key: emacs-${{ matrix.emacs-version }}

      - name: Install Emacs
        if: matrix.dist != 'arch' && steps.emacs-cache.outputs.cache-hit != 'true'
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Install Doom
        run: |
          cd ~ && ~/.emacs.d/bin/doom install --force --no-fonts --no-env --verbose

      - run: cd ~ && ls -la ~/.emacs.d/.local

      - name: Create tar archive
        run: cd ~ && tar -czf release-${{ matrix.dist }}.tar.gz ~/.emacs.d/.local

      - run: cd ~ && ls -la

      - name: Upload release artifact
        uses: actions/upload-artifact@main
        with:
          name: release-${{ matrix.dist }}
          path: ~/release-${{ matrix.dist }}.tar.gz

      # - run: ls -al $HOME/.emacs.d

      # - run: diff -qr doom-tmp $HOME/.emacs.d

    #   # - name: Save results
    #   #   uses: actions/upload-artifact@v4
    #   #   with:
    #   #     name: doom-files
    #   #     path:
